// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class HorseRaceCloudCodeBindings
    {
        readonly ICloudCodeService k_Service;

        public HorseRaceCloudCodeBindings(ICloudCodeService service)
        {
            k_Service = service;
        }
        public async Task RegisterVenue(string _venueData)
        {
            await k_Service.CallModuleEndpointAsync("HorseRaceCloudCode", "RegisterVenue",
                new Dictionary<string, object>() { { "venueData", _venueData } });
        }
        public async Task ScheduleRaceTimings(string _playerID, string _raceData)
        {
            await k_Service.CallModuleEndpointAsync("HorseRaceCloudCode", "RaceScheduleTimings",
               new Dictionary<string, object>() { { "playerID", _playerID }, { "raceData", _raceData } });
        }
        public async Task<string> VenueCheckIn(string checkInData)
        {
           return await k_Service.CallModuleEndpointAsync("HorseRaceCloudCode", "CheckedInVenue",
                new Dictionary<string, object>() { { "checkInData", checkInData } });
        }
    }
}
